package com.mituuz.fuzzier;

import com.intellij.ui.EditorTextField;
import com.intellij.ui.components.JBList;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class FuzzyFinder extends JPanel {
    private JEditorPane previewPane;
    private JBList<String> fileList;
    private EditorTextField searchField;
    private JPanel fuzzyPanel;

    public JEditorPane getPreviewPane() {
        return previewPane;
    }

    public JBList<String> getFileList() {
        return fileList;
    }

    public EditorTextField getSearchField() {
        return searchField;
    }

    public JPanel getFuzzyPanel() {
        return fuzzyPanel;
    }

    public void setFuzzyPanel(JPanel fuzzyPanel) {
        this.fuzzyPanel = fuzzyPanel;
    }

    private void createUIComponents() {
        this.setLayout(new BorderLayout());
        fuzzyPanel = new JPanel();
        this.add(fuzzyPanel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        fuzzyPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        searchField = new EditorTextField();
        searchField.setText("");
        fuzzyPanel.add(searchField, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        fuzzyPanel.add(scrollPane1, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        fileList = new JBList();
        scrollPane1.setViewportView(fileList);
        previewPane = new JTextPane();
        previewPane.setText("This is a text");
        fuzzyPanel.add(previewPane, new GridConstraints(0, 1, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(50, 50), new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return fuzzyPanel;
    }

}
