package com.mituuz.fuzzier;

import com.intellij.ui.EditorTextField;
import com.intellij.ui.components.JBList;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class FuzzyFinder extends JPanel {
    private JTextPane textPane1;
    private JBList<?> fileList;
    private EditorTextField searchField;
    private JPanel fuzzyPanel;

    public JTextPane getTextPane1() {
        return textPane1;
    }

    public JBList<?> getFileList() {
        return fileList;
    }

    public EditorTextField getSearchField() {
        return searchField;
    }

    public JPanel getFuzzyPanel() {
        return fuzzyPanel;
    }

    public void setFuzzyPanel(JPanel fuzzyPanel) {
        this.fuzzyPanel = fuzzyPanel;
    }

    private void createUIComponents() {
        this.setLayout(new BorderLayout());
        fuzzyPanel = new JPanel();
        this.add(fuzzyPanel);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        fuzzyPanel.setLayout(new GridLayoutManager(6, 6, new Insets(0, 0, 0, 0), -1, -1));
        textPane1 = new JTextPane();
        fuzzyPanel.add(textPane1, new GridConstraints(0, 5, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, new Dimension(50, 50), new Dimension(150, 50), null, 0, false));
        final Spacer spacer1 = new Spacer();
        fuzzyPanel.add(spacer1, new GridConstraints(0, 4, 6, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        fileList = new JBList();
        fuzzyPanel.add(fileList, new GridConstraints(0, 0, 5, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        searchField = new EditorTextField();
        fuzzyPanel.add(searchField, new GridConstraints(5, 0, 1, 4, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return fuzzyPanel;
    }
}
